### ISSUE TITLE
how to use the code?

### ISSUE THREAD

**Issue by luckyboysmith** [QingboKang/An-SVD-based-Fragile-Watermarking-Scheme-With-Grouped-Blocks#2]
helllo.wonderful paper and code
but,
how to use the code?
which .m file to run?

**Comment by luckyboysmith** [comment]
@qdsclove

**Comment by luckyboysmith** [comment]
looking forwoard to get your help.thanks
i am a green hand to watermarking,
thanks

**Comment by EnNaenna** [comment]
@luckyboysmith 
hello, have you known how to use the code?

**Comment by fusufen4** [comment]
@qdsclove  Is there something missing？which the main program？

**Comment by AhTeng94** [comment]
so anyone know how to run the code?

**Comment by AhTeng94** [comment]
@luckyboysmith 

> so anyone know how to run the code?

@luckyboysmith @EnNaenna @fusufen4

**Comment by QingboKang** [comment]
Hi all,

I am the author of this repository, sorry I am late. It provides two interface functions, for add watermark, you should directly call AddFragileWatermark, for extract watermark, you should directly call ExtractFragileWatermark, which these two have corresponding .m files.

Writing a script to call these two functions.

I think I should have the demo code for add and extract watermark, but I don't find it, it has been too long. If you guys still need help, I will write a demo code to illustrate how to use it.

Thanks.

**Comment by AhTeng94** [comment]
i can run the codes but now the things is it cant localize the tampered area.... can i know how you tamper the images, and saving in which formats? 
thanksss
